create table if not exists public.study_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  response_id text not null,
  response_at timestamptz not null,
  name text not null default '',
  gender text not null default '',
  correct integer not null default 0,
  total integer not null default 0,
  avg_conf double precision not null default 0,
  avg_time double precision not null default 0,
  total_time_ms bigint not null default 0,
  fastest_map text not null default '',
  hardest_reasons jsonb not null default '[]'::jsonb,
  entries_json jsonb not null default '[]'::jsonb,
  app text not null default '',
  page text not null default ''
);

create unique index if not exists study_responses_response_id_idx
  on public.study_responses (response_id);

create table if not exists public.study_response_entries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  response_id text not null,
  question_order integer not null default 0,
  dataset_key text not null default '',
  dataset_label text not null default '',
  answer text not null default '',
  confidence integer not null default 0,
  time_ms bigint not null default 0,
  correct boolean not null default false,
  app text not null default '',
  page text not null default ''
);

create index if not exists study_response_entries_response_id_idx
  on public.study_response_entries (response_id);

create table if not exists public.avatar_matches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  match_id text not null,
  match_at timestamptz not null,
  person_name text not null default '',
  state_name text not null default '',
  avatar_key text not null default 'default',
  source text not null default '',
  map_key text not null default '',
  app text not null default '',
  page text not null default ''
);

create unique index if not exists avatar_matches_match_id_idx
  on public.avatar_matches (match_id);

alter table public.study_responses enable row level security;
alter table public.study_response_entries enable row level security;
alter table public.avatar_matches enable row level security;

drop policy if exists "allow anon inserts to study_responses" on public.study_responses;
create policy "allow anon inserts to study_responses"
  on public.study_responses
  for insert
  to anon
  with check (true);

drop policy if exists "allow anon inserts to avatar_matches" on public.avatar_matches;
create policy "allow anon inserts to avatar_matches"
  on public.avatar_matches
  for insert
  to anon
  with check (true);

drop policy if exists "allow anon inserts to study_response_entries" on public.study_response_entries;
create policy "allow anon inserts to study_response_entries"
  on public.study_response_entries
  for insert
  to anon
  with check (true);

drop policy if exists "allow anon selects from avatar_matches" on public.avatar_matches;
create policy "allow anon selects from avatar_matches"
  on public.avatar_matches
  for select
  to anon
  using (true);
